services:
  postgres:
    image: postgres:16-alpine
    container_name: the-famous-db
    restart: unless-stopped
    environment:
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:       ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # auth-service:
  #   build:
  #     context: ./apps/auth-service
  #     dockerfile: Dockerfile
  #   container_name: auth-service
  #   restart: unless-stopped
  #   env_file: .env
  #   ports:
  #     - "${AUTH_SERVICE_PORT}:3001"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  # web:
  #   build:
  #     context: ./apps/web
  #     dockerfile: Dockerfile
  #   container_name: web
  #   restart: unless-stopped
  #   env_file: .env
  #   ports:
  #     - "${WEB_PORT}:3000"
  #   environment:
  #     - NEXT_PUBLIC_AUTH_SERVICE_URL=http://auth-service:3001
  #   depends_on:
  #     - auth-service

volumes:
  postgres_data: