name: 'Sub-workflow: Construcción de Contenedores'

on:
  workflow_call:

jobs:
  docker-build:
    name: 'Construir Contenedores'
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir y exportar - auth-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/auth-service/Dockerfile
          tags: auth-service:latest
          outputs: type=docker,dest=auth-service.tar

      - name: Construir y exportar - inventory-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/inventory-service/Dockerfile
          tags: inventory-service:latest
          outputs: type=docker,dest=inventory-service.tar

      - name: Construir y exportar - web
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/web/Dockerfile
          tags: web:latest
          outputs: type=docker,dest=web.tar

      - name: Construir y exportar - media-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/media-service/Dockerfile
          tags: media-service:latest
          outputs: type=docker,dest=media-service.tar

      - name: Subir Artifact - auth-service
        uses: actions/upload-artifact@v4
        with:
          name: auth-service-image
          path: auth-service.tar
          retention-days: 1

      - name: Subir Artifact - inventory-service
        uses: actions/upload-artifact@v4
        with:
          name: inventory-service-image
          path: inventory-service.tar
          retention-days: 1

      - name: Subir Artifact - web
        uses: actions/upload-artifact@v4
        with:
          name: web-image
          path: web.tar
          retention-days: 1

      - name: Subir Artifact - media-service
        uses: actions/upload-artifact@v4
        with:
          name: media-service-image
          path: media-service.tar
          retention-days: 1
