name: 'Calidad de Código y Formato'

on:
  push:
    branches: [github-actions]
  pull_request:
    branches: [github-actions]

env:
  NODE_VERSION: '20'
  GLOBAL_LOG_LEVEL: 'info'
  DEFAULT_DATABASE_NAME: 'the_famous_erp_test'

jobs:
  lint:
    name: 'Linting'
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Instalar Dependencias
        run: npm ci

      - name: Generar Cliente Prisma (Turborepo)
        env:
          DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/${{ env.DEFAULT_DATABASE_NAME }}'
        run: |
          echo "Generando base de datos cliente usando: $DATABASE_URL"
          npm run db:generate

      - name: Ejecutar Linter (Turborepo)
        run: npm run lint
